[package]
name = "shorting"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
rand = "0.9.2"
actix-cors = "0.7.1"
